import type { Product } from "./products";

const tuyaPairing = "Tuya Zigbee support stated; confirm final pairing before order";

export const controlPanelExpansion: Product[] = [
  {
    sku: "KI-TAOS-CP-SCPNS35",
    model: "SCP-NS3.5",
    name: "3.5-inch Zigbee relay control panel",
    category: "Control panels",
    categoryKey: "panels",
    family: "Compact relay panels",
    image: "scp-ns3-5.webp",
    protocol: "Zigbee / RS485 reserved",
    ecosystem: "Tuya Zigbee support stated",
    gateway: "Confirm gateway role with supplier",
    neutral: "86-type junction box",
    electrical: "4-channel relay; load rating not stated",
    size: "86 x 86 x 40.5mm",
    salesPath: "Configure a project",
    launchTier: "Conditional",
    cataloguePage: 30,
    note: "3.5-inch 320 x 480 display with radar wake, eight scenes, curtain and dimming controls; power and relay ratings require confirmation.",
  },
  {
    sku: "KI-TAOS-CP-SCPTS35",
    model: "SCP-TS3.5",
    name: "3.5-inch Wi-Fi, Sigmesh and IR control panel",
    category: "Control panels",
    categoryKey: "panels",
    family: "Compact relay panels",
    image: "scp-ts3-5.webp",
    protocol: "Wi-Fi / Sigmesh / IR",
    ecosystem: "Supplier mobile-app control stated; Tuya pairing not stated",
    gateway: "Not stated",
    neutral: "Mains-powered; 86-type base",
    electrical: "AC 100-240V; 3 x 200W; 600W total",
    size: "86 x 86 x 36.5mm with base",
    salesPath: "Configure a project",
    launchTier: "Conditional",
    cataloguePage: 30,
    note: "Three physical buttons, three relays and built-in infrared emitters; exact app and ecosystem must be confirmed.",
  },
  {
    sku: "KI-TAOS-CP-SCPTS4",
    model: "SCP-TS4",
    name: "4-inch Zigbee and Bluetooth Mesh control panel",
    category: "Control panels",
    categoryKey: "panels",
    family: "Compact gateway panels",
    image: "scp-ts4.webp",
    protocol: "Wi-Fi / Zigbee / Bluetooth Mesh",
    ecosystem: "Supplier states Zigbee and Bluetooth Mesh gateway functions",
    gateway: "Built in",
    neutral: "Mains-powered; EU base",
    electrical: "AC 100-240V",
    size: "86 x 86 x 36.2mm with base",
    salesPath: "Configure a project",
    launchTier: "Core",
    cataloguePage: 29,
    note: "4-inch 480 x 480 Linux panel with Alexa built-in, dual microphones and 1W speaker; final Tuya pairing must be confirmed.",
  },
  {
    sku: "KI-TAOS-CP-SCPNS6",
    model: "SCP-NS6",
    name: "6-inch Tuya Zigbee gateway control panel",
    category: "Control panels",
    categoryKey: "panels",
    family: "Central gateway panels",
    image: "scp-ns6.webp",
    protocol: "Wi-Fi / Ethernet / Zigbee 3.0 / Bluetooth / RS485",
    ecosystem: tuyaPairing,
    gateway: "Tuya Zigbee gateway stated",
    neutral: "Mains-powered; single 86 box",
    electrical: "AC 110-250V; 2-channel light control below 200W",
    size: "208 x 86 x 11.5mm",
    salesPath: "Configure a project",
    launchTier: "Extended",
    cataloguePage: 30,
    note: "6-inch 1440 x 720 display plus 1.28-inch round screen; Android 8.1, 2GB RAM and 8GB storage are supplier-stated.",
  },
  {
    sku: "KI-TAOS-CP-SCPTS8",
    model: "SCP-TS8",
    name: "8-inch Zigbee and Bluetooth gateway control panel",
    category: "Control panels",
    categoryKey: "panels",
    family: "Central gateway panels",
    image: "scp-ts8.webp",
    protocol: "Wi-Fi / Ethernet / Zigbee / Bluetooth",
    ecosystem: "Supplier states Zigbee and Bluetooth Mesh/BLE gateway functions",
    gateway: "Built in",
    neutral: "Mains-powered; EU base",
    electrical: "AC 100-240V",
    size: "127.5 x 233.5 x 38mm with base",
    salesPath: "Configure a project",
    launchTier: "Extended",
    cataloguePage: 30,
    note: "8-inch 1280 x 800 Android panel with Alexa built-in and temperature/humidity sensing; final ecosystem pairing must be confirmed.",
  },
  {
    sku: "KI-TAOS-CP-SCPNS8",
    model: "SCP-NS8",
    name: "8-inch Tuya Zigbee audio and intercom control panel",
    category: "Control panels",
    categoryKey: "panels",
    family: "Audio & intercom panels",
    image: "scp-ns8.webp",
    protocol: "Wi-Fi / Ethernet / Zigbee 3.0 / Bluetooth / RS485",
    ecosystem: tuyaPairing,
    gateway: "Tuya Zigbee gateway stated",
    neutral: "AC 110-250V; secondary input option requires confirmation",
    electrical: "2-channel strong-current control; each channel below 200W",
    size: "250 x 133 x 10mm",
    salesPath: "Configure a project",
    launchTier: "Conditional",
    cataloguePage: 30,
    note: "8-inch 1280 x 800 display with round sub-screen, audio input/output, amplified speaker output and building-intercom interface.",
  },
  {
    sku: "KI-TAOS-CP-SCPTS10",
    model: "SCP-TS10",
    name: "10.1-inch whole-home central control panel",
    category: "Control panels",
    categoryKey: "panels",
    family: "Central gateway panels",
    image: "scp-ts10.webp",
    protocol: "Wi-Fi / Ethernet / Zigbee / Bluetooth / RS485",
    ecosystem: "Supplier states Zigbee and Bluetooth Mesh/BLE gateway functions",
    gateway: "Built in",
    neutral: "Mains or 12V DC; EU base",
    electrical: "AC 100-240V or 12V DC; 2-way relay stated",
    size: "259 x 161 x 39mm with base",
    salesPath: "Configure a project",
    launchTier: "Extended",
    cataloguePage: 29,
    note: "10.1-inch 1920 x 1200 Android panel with Alexa, front camera and temperature/humidity sensors; final Tuya integration must be confirmed.",
  },
  {
    sku: "KI-TAOS-CP-SCPNS12",
    model: "SCP-NS12",
    name: "12.3-inch Tuya Zigbee audio and intercom control panel",
    category: "Control panels",
    categoryKey: "panels",
    family: "Audio & intercom panels",
    image: "scp-ns12.webp",
    protocol: "Wi-Fi / Ethernet / Zigbee 3.0 / Bluetooth / RS485",
    ecosystem: tuyaPairing,
    gateway: "Tuya Zigbee gateway stated",
    neutral: "Mains-powered; single or double 86 box",
    electrical: "AC 110-250V; 2-channel strong-current control; each channel below 200W",
    size: "357 x 143.5 x 13.5mm",
    salesPath: "Configure a project",
    launchTier: "Conditional",
    cataloguePage: 30,
    note: "12.3-inch 1920 x 720 Android 11 panel with audio input/output and 2 x 25W amplified speaker output.",
  },
];
