import type { Product } from "./products";

const supplierPairing = "Tuya/Smart Life pairing confirmed before order";

const ledControl: Product[] = [
  {
    sku: "KI-TAOS-LD-ZANCS240LCCW",
    model: "ZAN-CS240LC-CW",
    name: "Zigbee CW LED-strip controller",
    category: "LED control",
    categoryKey: "drivers",
    family: "LED controllers",
    image: "zan-cs240lc-cw.webp",
    protocol: "Zigbee 3.0",
    ecosystem: supplierPairing,
    gateway: "Required",
    neutral: "DC input",
    electrical: "DC 12-24V; max 240W; 10A",
    size: "Confirm with supplier",
    salesPath: "Buy with installation",
    launchTier: "Core",
    cataloguePage: 31,
    note: "Constant-white LED-strip controller; confirm strip voltage and total load.",
  },
  {
    sku: "KI-TAOS-LD-ZANCS240LCRGBCW",
    model: "ZAN-CS240LC-RGBCW",
    name: "Zigbee RGBCW LED-strip controller",
    category: "LED control",
    categoryKey: "drivers",
    family: "LED controllers",
    image: "zan-cs240lc-rgbcw.webp",
    protocol: "Zigbee 3.0",
    ecosystem: supplierPairing,
    gateway: "Required",
    neutral: "DC input",
    electrical: "DC 12-24V; max 240W; 10A",
    size: "Confirm with supplier",
    salesPath: "Buy with installation",
    launchTier: "Core",
    cataloguePage: 31,
    note: "RGB plus tunable-white control; confirm channel configuration and strip type.",
  },
  {
    sku: "KI-TAOS-LD-ZANS100LC",
    model: "ZAN-S100LC",
    name: "100W Zigbee dimmable colour-adjustable power supply",
    category: "LED control",
    categoryKey: "drivers",
    family: "Power supplies",
    image: "zan-s100lc.webp",
    protocol: "Zigbee 3.0",
    ecosystem: supplierPairing,
    gateway: "Required",
    neutral: "Mains-powered",
    electrical: "175-265V input; 24V / 4A output; max 100W",
    size: "Confirm with supplier",
    salesPath: "Configure a project",
    launchTier: "Extended",
    cataloguePage: 31,
    note: "Specify the connected lighting load and required colour-control mode.",
  },
];

const magneticLights = [
  ["EU-M20-D7", "7W smart magnetic downlight", "Magnetic downlights", "7W", "15° / 24° / 36°", "Ø45 x L100mm", "Bridgelux"],
  ["EU-M20-D12", "12W smart magnetic downlight", "Magnetic downlights", "12W", "15° / 24° / 36°", "Ø55 x L120mm", "Bridgelux"],
  ["EU-M20-D20", "20W smart magnetic downlight", "Magnetic downlights", "20W", "15° / 24° / 36°", "Ø65 x L140mm", "Bridgelux"],
  ["EU-M20-F12", "12W smart magnetic flood light", "Magnetic flood lights", "12W", "120°", "L300 x W22 x H25mm", "Osram"],
  ["EU-M20-F18", "18W smart magnetic flood light", "Magnetic flood lights", "18W", "120°", "L600 x W22 x H25mm", "Osram"],
  ["EU-M20-F36", "36W smart magnetic flood light", "Magnetic flood lights", "36W", "120°", "L1200 x W22 x H25mm", "Osram"],
  ["EU-M20-G6", "6W smart magnetic grille light", "Magnetic grille lights", "6W", "24° / 36°", "L110 x W22 x H25mm", "Osram"],
  ["EU-M20-G12", "12W smart magnetic grille light", "Magnetic grille lights", "12W", "24° / 36°", "L220 x W22 x H25mm", "Osram"],
  ["EU-M20-G18", "18W smart magnetic grille light", "Magnetic grille lights", "18W", "24° / 36°", "L338 x W22 x H25mm", "Osram"],
  ["EU-M20-G24", "24W smart magnetic grille light", "Magnetic grille lights", "24W", "24° / 36°", "L452 x W22 x H25mm", "Osram"],
  ["EU-M20-FG6", "6W smart magnetic folding grille light", "Folding grille lights", "6W", "24°", "L112 x W22 x H136mm", "Osram"],
  ["EU-M20-FG12", "12W smart magnetic folding grille light", "Folding grille lights", "12W", "24°", "L225 x W22 x H136mm", "Osram"],
] as const;

const magneticProducts: Product[] = magneticLights.map(
  ([model, name, family, power, beam, size, chip]) => ({
    sku: `KI-TAOS-LI-${model.replace(/[^a-z0-9]/gi, "").toUpperCase()}`,
    model,
    name,
    category: "Smart lighting",
    categoryKey: "lighting",
    family,
    image: `${model.toLowerCase()}.webp`,
    protocol: "Zigbee 3.0",
    ecosystem: supplierPairing,
    gateway: "Required",
    neutral: "48V magnetic track system",
    electrical: `${power}; ${beam} beam`,
    size,
    salesPath: "Configure a project",
    launchTier: model === "EU-M20-D12" ? "Core" : "Extended",
    cataloguePage: 33,
    note: `Black aluminium body; ${chip} LED; RA ≥ 90; order 3000K, 4000K or 6000K.`,
  })
);

const systemAccessories: Product[] = [
  {
    sku: "KI-TAOS-LI-48VPS100",
    model: "48V-PS100",
    name: "48V 100W magnetic-track power supply",
    category: "Smart lighting",
    categoryKey: "lighting",
    family: "Track & power",
    image: "48v-ps100.webp",
    protocol: "System component",
    ecosystem: "For the TAOS 48V magnetic-track lighting family",
    gateway: "Not applicable",
    neutral: "160-260V input; 48V output",
    electrical: "100W; overload and over-temperature protection",
    size: "225 x 22 x 43mm",
    salesPath: "Configure a project",
    launchTier: "Extended",
    cataloguePage: 34,
    note: "Select only after calculating the connected track-light load.",
  },
  {
    sku: "KI-TAOS-LI-48VPS200",
    model: "48V-PS200",
    name: "48V 200W magnetic-track power supply",
    category: "Smart lighting",
    categoryKey: "lighting",
    family: "Track & power",
    image: "48v-ps200.webp",
    protocol: "System component",
    ecosystem: "For the TAOS 48V magnetic-track lighting family",
    gateway: "Not applicable",
    neutral: "160-260V input; 48V output",
    electrical: "200W; overload and over-temperature protection",
    size: "225 x 22 x 43mm",
    salesPath: "Configure a project",
    launchTier: "Extended",
    cataloguePage: 34,
    note: "Select only after calculating the connected track-light load.",
  },
  {
    sku: "KI-TAOS-LI-M20RTA",
    model: "M20-RT-A",
    name: "20 recessed magnetic track - profile A",
    category: "Smart lighting",
    categoryKey: "lighting",
    family: "Track & power",
    image: "m20-rt-a.webp",
    protocol: "System component",
    ecosystem: "For the TAOS 20 magnetic-track lighting family",
    gateway: "Not applicable",
    neutral: "Four-wire red-copper track",
    electrical: "48V magnetic-track system",
    size: "1m / 2m / 3m; 34mm cut-out",
    salesPath: "Configure a project",
    launchTier: "Conditional",
    cataloguePage: 34,
    note: "Supplier catalogue does not show a separate model code; profile and ceiling detail must be confirmed.",
  },
  {
    sku: "KI-TAOS-LI-M20RTB",
    model: "M20-RT-B",
    name: "20 recessed magnetic track - profile B",
    category: "Smart lighting",
    categoryKey: "lighting",
    family: "Track & power",
    image: "m20-rt-b.webp",
    protocol: "System component",
    ecosystem: "For the TAOS 20 magnetic-track lighting family",
    gateway: "Not applicable",
    neutral: "Four-wire red-copper track",
    electrical: "48V magnetic-track system",
    size: "1m / 2m / 3m; 34mm cut-out",
    salesPath: "Configure a project",
    launchTier: "Conditional",
    cataloguePage: 34,
    note: "Supplier catalogue does not show a separate model code; profile and ceiling detail must be confirmed.",
  },
  {
    sku: "KI-TAOS-LI-M20ST",
    model: "M20-ST",
    name: "20 surface or suspended magnetic track",
    category: "Smart lighting",
    categoryKey: "lighting",
    family: "Track & power",
    image: "m20-st.webp",
    protocol: "System component",
    ecosystem: "For the TAOS 20 magnetic-track lighting family",
    gateway: "Not applicable",
    neutral: "Four-wire red-copper track",
    electrical: "48V magnetic-track system",
    size: "1m / 2m / 3m",
    salesPath: "Configure a project",
    launchTier: "Conditional",
    cataloguePage: 34,
    note: "Surface and suspended installation options require a project-specific accessory schedule.",
  },
];

const recessedLights = [
  ["CK-S001-10", "10W Zigbee smart spotlight - S001", "85 x 87mm", "38°"],
  ["CK-S002-10", "10W Zigbee smart spotlight - S002", "85 x 76mm", "38°"],
  ["CK-S003-10", "10W Zigbee smart spotlight - S003", "85 x 90mm", "38°"],
  ["CK-D001-10", "10W Zigbee smart downlight", "82 x 55mm", "60°"],
] as const;

const recessedProducts: Product[] = recessedLights.map(([model, name, size, beam]) => ({
  sku: `KI-TAOS-LI-${model.replace(/[^a-z0-9]/gi, "").toUpperCase()}`,
  model,
  name,
  category: "Smart lighting",
  categoryKey: "lighting",
  family: model.startsWith("CK-D") ? "Downlights" : "Spotlights",
  image: `${model.toLowerCase()}.webp`,
  protocol: "Zigbee 3.0",
  ecosystem: supplierPairing,
  gateway: "Required",
  neutral: "Mains-powered",
  electrical: `10W; ${beam} beam`,
  size,
  salesPath: "Buy with installation",
  launchTier: model === "CK-S001-10" || model === "CK-D001-10" ? "Core" : "Extended",
  cataloguePage: 34,
  note: "Aluminium body; Bridgelux LED; RA ≥ 98; tunable 2700K-6400K.",
}));

const ledStrips: Product[] = [
  {
    sku: "KI-TAOS-LI-OE08MMSS01",
    model: "OE-08MM-SS01",
    name: "24V high-output smart-system LED strip",
    category: "Smart lighting",
    categoryKey: "lighting",
    family: "LED strips",
    image: "oe-08mm-ss01.webp",
    protocol: "Requires compatible controller",
    ecosystem: "Pair with the selected Zigbee LED controller",
    gateway: "Depends on controller",
    neutral: "24V DC",
    electrical: "20W/m; 145 lm/W; 120 LEDs/m",
    size: "8 x 1000mm; 66.66mm cutting length",
    salesPath: "Configure a project",
    launchTier: "Extended",
    cataloguePage: 34,
    note: "RA ≥ 90; specify 2700K-6400K output and total run length before selecting a driver.",
  },
  {
    sku: "KI-TAOS-LI-OE10MMCS01",
    model: "OE-10MM-CS01",
    name: "24V dual-channel tunable-white LED strip",
    category: "Smart lighting",
    categoryKey: "lighting",
    family: "LED strips",
    image: "oe-10mm-cs01.webp",
    protocol: "Requires compatible controller",
    ecosystem: "Pair with the selected Zigbee LED controller",
    gateway: "Depends on controller",
    neutral: "24V DC",
    electrical: "7W + 7W/m; 90 lm/W",
    size: "10 x 1000mm; 26.31mm cutting length",
    salesPath: "Configure a project",
    launchTier: "Extended",
    cataloguePage: 34,
    note: "RA ≥ 90; tunable 2700K-6400K; driver and controller are sized to the complete run.",
  },
];

export const lightingExpansion: Product[] = [
  ...ledControl,
  ...magneticProducts,
  ...systemAccessories,
  ...recessedProducts,
  ...ledStrips,
];
